### ISSUE TITLE
Lightning talks f. nächstes Meetup am 24.6.2015?

### ISSUE THREAD

**Issue by nicodh** [devsmeetup/forum#10]
Hallo zusammen,

da wir noch keinen Vortrag für das nächste Meeting haben, sollte es ein paar Lightning talks geben. Dafür bräuchten wir ein paar Vorschläge. Ein immer wiederkehrendes Thema das ich gerne mal in der Runde diskutieren würde: wie evaluiert Ihr Frameworks, welche verwendet Ihr, framework vs. libraries etc.

**Comment by jayeff** [comment]
Diskussion zu Framework/Library Evaluierung klingt gut.

Ich kann mal den vorgeschlagene Einführung in Usability Testing Talk machen. Ich denke 15-20 Minuten ist ausreichend.

**Comment by nicodh** [comment]
Das fände ich gut. Ich würde dann die Diskussion zu den Frameworks einleiten (aber keinen Vortrag halten).
