### ISSUE TITLE
lightning talks für Juli 2015?

### ISSUE THREAD

**Issue by rupl** [devsmeetup/forum#11]
ich könnte einen kleinen Talk zu "visual web sockets" halten. ich hab kürzlich ein paar projekte entwickelt.

**Comment by stmllr** [comment]
\o/

**Comment by sebald** [comment]
Super! Wenn du magst, kannst du den Talk auch gerne auf Englisch halten :)
Wie lange würde denn der Talk dauern?

**Comment by rupl** [comment]
ja gut! Mein Deutsch ist ok für einfache Sachen, aber nicht gut genug für komplizierte Themen :bowtie: 

15min würde ich sagen? oder vielleicht 30. Beide passen. Den Talk wird spontan sein, ihn ist noch nicht geschrieben.

**Comment by sebald** [comment]
Du kannst einfach auch hin und her wechseln ;D Das wird keinen stören.
Zwischen 15 und 30min sind auf jeden fall ausreichend.

Ich werd heute Abend einen PR aufmachen, in den kannst du dann deine Daten einfach einfügen :)
@nicodh Passt das?

**Comment by nicodh** [comment]
Ja das passt. Ich versuche dann heute noch das auf meetup.com einzutragen...
Wenn nicht schaffe ich es erst am Mittwoch

**Comment by stmllr** [comment]
awesome!

**Comment by sebald** [comment]
PR erstellt.
