### ISSUE TITLE
Talks for 30. September 2015

### ISSUE THREAD

**Issue by nicodh** [devsmeetup/forum#12]
Please add suggestions here...

**Comment by rupl** [comment]
~~Using WebPageTest? I can show a quick demo using before/after data I have laying around~~

actually for the 30th I can't present.. tut mir leid!

**Comment by MantasVaitkunas** [comment]
Hi everybody, if someone would be interested I could present how my team is using Jenkins CI in product development (for eCommerce platform), what issues we have and etc...

**Comment by nicodh** [comment]
Hi Mantas,
I guess you just used this old thread to propose a talk for this month?
For me it would be fine to hear about that topic!
Nico

**Comment by nicodh** [comment]
Maybe you propose it on https://www.meetup.com/Devsmeetup-Freiburg/ ...?

**Comment by MantasVaitkunas** [comment]
Hi @nicodh, sorry for putting it in wrong place. Could you be more precise as I never participated in Freiburg devs meetup and I added a topic as it was described in event description:

> Anyone is invited to give a talk (5-30 minutes long). Please suggest a topic in the github forum: ``https://github.com/devsmeetup/forum/issues/12``

Should I propose topic here: https://www.meetup.com/Devsmeetup-Freiburg/events/238052476/ ?

**Comment by nicodh** [comment]
Hi Mantas,
sorry for delay: https://www.meetup.com/Devsmeetup-Freiburg/messages/boards/thread/49616061 would be the right place.
Just post your announcement text there and I will anounce it for the next meetup, ok?

**Comment by MantasVaitkunas** [comment]
@nicodh, done :)
