### ISSUE TITLE
Talk oder Thema f. 25. Januar

### ISSUE THREAD

**Issue by nicodh** [devsmeetup/forum#14]
Bitte hier im Kommentar eintragen, wer einen Talk vorschlagen möchte oder ein Thema das diskutiert werden könnte...

**Comment by hpk42** [comment]
hey @nicodh !  Ich wollte auch wieder mal kommen und koennte auch was vortragen zu meinem neuen Projekt "Autocrypt: Email-encryption for everyone!", see https://autocrypt.readthedocs.io/en/latest/ -- der teaser waere z.b:

> Email has been declared dead many times but refuses to die. It remains the largest open federated identity and messaging system, anchors the web and mobile phones and continues to relay sensitive information between citizens and organisations.  However, bringing pervasive end-to-end encryption to this infrastructure has failed so far.  Autocrypt is a fresh approach which aims to establish cross-mail-program standards for encryption, using in-band key transfer.  It is driven by developers from several mail programs and researchers who convened in December 2016 and decided to go for the joined "Autocrypt" approach.  Holger is involved in organizing the Autocrypt efforts and introduces in this devsmeetup session Autocrypt features and what is planned to get going in Spring 2017: e-mail encryption for everyone! :)

**Comment by nicodh** [comment]
+1

**Comment by mcrot** [comment]
+1

**Comment by sebald** [comment]
Fände ich auch super spannend! Sollen wir das fest machen? :)

**Comment by nicodh** [comment]
@hpk42  Ich trag es ein, mit dem Teaser den du vorgeschlagen hast, ok?

**Comment by sebald** [comment]
@nicodh aktualisiert du direkt noch die Seite?

PS: Wir sollten vllt mal die Webseite aktualisieren, dass sie einfach die MeetupAPI verwendet und sich den neusten Talk holt. Nachteil wäre, dass wir keine Speaker mehr explizit angeben können.

**Comment by hpk42** [comment]
@nicodh alles klar!  freue mich endlich mal wieder dabei zu sein :)

**Comment by hpk42** [comment]
zur info: ich lege bei autocrypt keinen wert auf moeglichst grosse publicity oder tweets und autocrypt  kam bisher ganz gut ohne klar :) vielleicht waere ja eine devsmeetup mailingliste doch mal ganz nett ...

**Comment by sebald** [comment]
Keine Sorge, das können wir eh nicht ;D
