### ISSUE TITLE
Talk for Wednesday, 26. September 2018: Releases: Aus Jahren werden Minuten - Mehr Outcome mit weniger Einsatz

### ISSUE THREAD

**Issue by MortlMcCrisis** [devsmeetup/forum#15]
Hi zusammen,

ich halte einen Vortag bei der xCelerate im Oktober und würde diesen Vortrag gerne vorab auch hier im DevMeetup halten. Der Vortrag hat den Titel "Releases: Aus Jahren werden Minuten - Mehr Outcome mit weniger Einsatz". Darin erkläre ich was wir im Unternehmen alles unternommen haben um von einem Releasezyklus von einem Jahr auf monatliche Relases zu kommen und dabei nur noch wenige Minuten für ein Release brauchen.

**Comment by nicodh** [comment]
Hi, wir haben uns gerade intern abgestimmt: du kannst den Vortrag gerne halten, schick uns bitte noch ein Abstract sowie deinen Klarnamen. Ist der Vortrag auf deutsch oder englisch? Den abstract dann bitte in der gleichen Sprache...

**Comment by MortlMcCrisis** [comment]
Hi, sorry für die späte Antwort, ich war bis heute im Urlaub. 
Cool, das freu mich mich. Ich hänge den Abstract hier an. Der Vortrag wird auf deutsch sein. Mein Name ist Jan Mortensen.
[x-celerate-Abstract-Releases Aus Jahren werden Minuten.pdf](https://github.com/devsmeetup/forum/files/2387737/x-celerate-Abstract-Releases.Aus.Jahren.werden.Minuten.pdf)

**Comment by stmllr** [comment]
@MortlMcCrisis 

Hallo Jan,

danke dass Du den Vortrag beim devsmeetup halten möchtest.
Für unser meetup ist das Abstract zu lang. Kannst Du das bitte auf einen Absatz eindampfen?
Und noch eine kurze Bio posten (ein Satz).

Dann veröffentliche ich das auf meetup.com und auf der devsmeetup website

**Comment by MortlMcCrisis** [comment]
@stmllr 
Abstract:
Wie schaffe ich es den Deploymentzyklus einer schwergewichtigen Legacy-Applikation von vielen Monaten auf wenige Minuten zu reduzieren und gleichzeitig den nötigen Gesamtaufwand zu reduzieren? Hierzu sind sowohl technische als auch nicht-technische Maßnahmen, wie die Auswahl der richtigen Technologien oder die Optimierung von Firmenprozessen, erforderlich. Das Ausmaß solcher Optimierungen wird oftmals unterschätzt.

Bio:
Jan Mortensen hat an der Universität Freiburg Informatik studiert und arbeitet seit 4 Jahren beim E-Mail-Marketinganbieter Inxmail in Freiburg. Davon war er die ersten beiden in der Kernproduktentwicklung tätig und ist seit 2 Jahren Teil des Teams Release Train, wo er sich hauptsächlich mit dem Deploymentprozess beschäftigt.

Die Bio sind 2 Sätze geworden, daür beide relativ kurz ;-)

**Comment by stmllr** [comment]
@MortlMcCrisis https://www.meetup.com/de-DE/Devsmeetup-Freiburg/events/vlftklyxmbjc/
https://devsmeetup.de wird nächtlich aktualisiert

**Comment by stmllr** [comment]
@nicodh meetup.com ankündigung ist auch raus. Ich bin nächste Woche **nicht** da.
