### ISSUE TITLE
[Organisation] Vorschläge und Ideen für Talks

### ISSUE THREAD

**Issue by sebald** [devsmeetup/forum#2]
Wenn ihr Lust habt einen Talk zu halten oder jemanden kennt der umbedingt was vortragen soll, dann schreibt hier rein! :)

**Comment by mck9** [comment]
Eine Idee für eine (oder mehrere) Lightning Talk Runden: Entwurfsmuster
Der/Die Vortragende kann ein Entwurfsmuster mit einem Beispiel aus der Praxis vorstellen. Ich könnte was zu Strategie-Muster machen.

**Comment by stmllr** [comment]
@mck9 Wie wäre es mit Anti-Pattern? Das kommt in den Büchern immer zu kurz.

**Comment by mck9** [comment]
Da kenn ich mich nicht so aus :-)

Am 09.04.2014 11:44, schrieb Steffen Müller:

> @mck9 https://github.com/mck9 Wie wäre es mit Anti-Pattern? Das
> kommt in den Büchern immer zu kurz.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/devsmeetup/forum/issues/2#issuecomment-39945914.

## 

marek kralewski
tuxwerk OHG | baslerstr 13 | 79100 freiburg
fon: +49 761 7043067
fax: +49 761 7043066

geschäftsführung: marek kralewski, johann kralewski
ust-idnr. DE270893097, handelsregister freiburg HRA 5159

**Comment by sebald** [comment]
Meinst du allgemeine "Software Design Pattern"?

**Comment by a-v-l** [comment]
@stmllr Schön fände ich eine Gegenüberstellung: Oft angetroffene Anti-Pattern für ein bestimmtes Problem und ordentlich umgesetzte Lösung mit erprobtem Entwurfsmuster – Also: Problem -> Dos & Don'ts

**Comment by mck9** [comment]
OpenSSL würde sich für die "Don'ts" anbieten. Aber das "Dos" zu finden wird hart.

**Comment by a-v-l** [comment]
@mck9 Verstehe ich nicht, seit wann ist OpenSSL ein [Entwurfsmuster](http://c2.com/cgi/wiki?DesignPatternsBook)?

Was ich meinte ist, dass man gerade als unerfahrener Programmierer nicht alle Standardlösungen kennt und sich dann eben eine einfache & schnelle Lösung zusammenfrickelt und hinterher über die schlechte Wartbarkeit/Erweiterbarkeit des Codes ärgert. Auf der anderen Seite gibt es eine Menge [Patterns](http://addyosmani.com/resources/essentialjsdesignpatterns/book/), die sich oft erst in der Praxis erschließen und nur schlecht wie Vokabeln "pauken" lassen. Zumindest geht das mir teilweise so. Deshalb wäre es nett, nicht nur die glänzende "Best Practice" vorgestellt zu bekommen, sondern ähnlich wie in dem Buch "[Clean Code](http://www.amazon.de/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)" einen unguten aber üblichen Ansatz und dann meinetwegen das Refactroring mit einem soliden Pattern.

Kleines Beispiel in JS:

``` js
//DON'T
var myArray = new Array ("foo", "bar", "baz", "qux");
for (var i = 0; i <= myArray.length; i++) {
    // do stuff
}
```

``` js
//DO
var myArray = ["foo", "bar", "baz", "qux"],
    i,
    max;
for (i = 0, max = myArray.length; i <= max; i += 1) {
    // do stuff
}
```

btw: OpenSSL ist in privaten Projekten (OwnClowd, RoundCube, etc.) doch wunderbar - das Update auf [1.0.1g](http://heartbleed.com/) hat ja inzwischen hoffentlich jede/r aufgespielt ;)

**Comment by mck9** [comment]
@a-v-l OpenSSL ist natürlich kein Entwurfsmuster, sondern ein Anti-Pattern :-)

Ich meinte natürlich dasselbe und ein wenig scherzhaft dazu, zudem bin ich mir sicher, dass OpenSSL eine gute Fundgrube für Anti-Patterns darstellt und Hilfe braucht. Ein kleiner Auszug aus ssl/tls_srp.c zum Vergnügen (finde das Anti-Pattern!):

``` c
    if (N!= NULL)
        {
        if (s->srp_ctx.N != NULL)
            {
            if (!BN_copy(s->srp_ctx.N,N))
                {
                BN_free(s->srp_ctx.N);
                s->srp_ctx.N = NULL;
                }
            }
        else
            s->srp_ctx.N = BN_dup(N);
        }
    if (g!= NULL)
        {
        if (s->srp_ctx.g != NULL)
            {
            if (!BN_copy(s->srp_ctx.g,g))
                {
                BN_free(s->srp_ctx.g);
                s->srp_ctx.g = NULL;
                }
            }
        else
            s->srp_ctx.g = BN_dup(g);
        }
    if (sa!= NULL)
        {
        if (s->srp_ctx.s != NULL)
            {
            if (!BN_copy(s->srp_ctx.s,sa))
                {
                BN_free(s->srp_ctx.s);
                s->srp_ctx.s = NULL;
                }
            }
        else
            s->srp_ctx.s = BN_dup(sa);
        }
    if (v!= NULL)
        {
        if (s->srp_ctx.v != NULL)
            {
            if (!BN_copy(s->srp_ctx.v,v))
                {
                BN_free(s->srp_ctx.v);
                s->srp_ctx.v = NULL;
                }
            }
        else
            s->srp_ctx.v = BN_dup(v);
        }
```

btw: ein Update ist nur eine Sache, aber dazu darfst Du gleich alle Keys neu erstellen und signieren lassen und am besten noch gleich alle Passworte neu setzen :-) Das ist noch die andere Sache, mit der wir vorgestern beschäftigt waren.
btw2: Theo de Raadt beschreibt hier eine der Hauptursachen für das Desaster: http://article.gmane.org/gmane.os.openbsd.misc/211963
btw3: Immer wieder schön: https://www.peereboom.us/assl/assl/html/openssl.html

**Comment by sebald** [comment]
So sieht halt Code aus, wenn er von Leuten geschrieben wird, die die meiste Zeit ihres Lebens Assembler geschrieben haben. Finde das nicht schlimm. Für diejenigen ist der Code bestimmt auch kein Anti-Pattern.

Aber zurück zum Thema! Bitte haltet dieses Thread möglichst sauber! :P
Wenn ihr euch darüber unterhalten wollt dürft ihr gerne ein Issue aufmachen! :)

**Comment by mck9** [comment]
Weiterer Vorschlag für einen Talk: Gibt es tatsächliche objektive Maßstäbe bei der Beurteilung von Code-Qualität oder handelt es sich viel mehr nur um Meinungen?

**Comment by sebald** [comment]
Ist das ein Talk den du halten magst? Vllt als Lightning Talk? ;)

**Comment by sebald** [comment]
@a-v-l Wie sieht es bei dir aus? Hast du Zeit und Lust im Juni einen Talk zu halten? :)

**Comment by a-v-l** [comment]
Sorry, die nächste Zeit sieht es schlecht aus bei mir – rein Zeitmässig. Aber evtl. kann ich was für den Herbst vorbereiten… Mal sehen. Ich melde mich!

**Comment by sebald** [comment]
Kein Ding. Dankte für die Info :-)
