### ISSUE TITLE
Workshop: Real World JavaScript

### ISSUE THREAD

**Issue by dignifiedquire** [devsmeetup/forum#3]
We talked about this tonight. I would like to organize/teach a short Javascript course on `Real World JavaScript`. 

Would like to get some feedback here on how many people would be interested in something like this or alternative ideas.

**Edit:** Renamed to `JavaScript in the real World`
**Edit2:** Renamed to `Real World JavaScript`

**Comment by sebald** [comment]
Why no _JavaScript in the real World_?

I think object-orientation is also an important part when using JS on real applications. Actually I think this is what made me fall in love with JavaScript. You can switch between these concepts so easily and do whatever is suited best for your problem.

**Comment by stmllr** [comment]
I'm in and I second Sebastians idea.

**Comment by mck9** [comment]
Dann noch gerne gewürzt mit einem kleinen Ausblick in die »Wundervolle Welt der Closures«!

**Comment by a-v-l** [comment]
Auch dabei!

**Comment by dignifiedquire** [comment]
I'm going through content ideas at the moment, so if anyone has suggestions or ideas that he would like to see let me know here :)

**Comment by a-v-l** [comment]
I'd be happy to see something like _»My set of indispensable helper methods I use all the time«_ included in the session…

**Comment by stmllr** [comment]
> Applying pattern of functional vs. object oriented patterns by example

**Comment by sebald** [comment]
@Dignifiedquire are you looking for a specific thing to talk about or a overall workshop theme?

**Comment by drublic** [comment]
Is there any idea on when this will happen?

**Comment by dignifiedquire** [comment]
@drublic as soon as I find time doing it. The plan was to get it out before the summer break but I guess that's not gonna happen, so I'm planning for September at the moment.

**Comment by drublic** [comment]
September sound good for me :) Let me know if I can do anything in advance to help with this project.

**Comment by dignifiedquire** [comment]
It's coming https://twitter.com/dignifiedquire/status/509361913122553856
