### ISSUE TITLE
Lightning Talks

### ISSUE THREAD

**Issue by jonasreinsch** [devsmeetup/forum#4]
Könnte man vielleicht bei jedem Devsmeetup machen - wenn jemand will, einfach 5 Minuten (oder 1-10Min) über ein Thema reden.

Oder könnte auch eine Lightning Talk Session sein, mit z.B. 6 Lightning Talks in einer Stunde (wenn genug mitmachen).

Bsp, über die ich z.B. mal was erzählen könnte:
- Ein paar Regex-Tricks, die ich super finde
- Ein paar Kommandozeilen-Tools, von denen ihr bestimmt noch nichts gehört habt :-)
- Usw

**Comment by sebald** [comment]
Finde ich gut, aber ich finde man sollte entweder einen Talk machen, die gehen ja momentan immer so 1-2 Stunden ;), oder ein paar Lightning Talks. Wir könnten das ja nächstes mal einfach ausprobieren, was meint ihr @nicodh @nimius-nicki ?

**Comment by nicki-schinow** [comment]
Gute Idee, denke jedoch auch, dass wir uns entscheiden sollten. Nächstes Mal klingt sehr gut!

**Comment by jonasreinsch** [comment]
ja, ist wahrscheinlich witziger und sinnvoller, wenn es ein paar Talks am Stück sind.
Hier
http://en.wikipedia.org/wiki/Lightning_talk
gabs noch nen Hinweis, dass es vielleicht Orga-mäßig gut wäre, wenn Slides etc. vorher gesammelt werden auf einem Rechner, so dass man nicht ständig umstöpseln muss.

"""[...] a single computer running a Presentation program is used by all speakers. In general lighting talks are given in a format that can include slides but if so, the speaker must be careful not to read the details which they include."""

**Comment by sebald** [comment]
Ja, das ist eine gute Idee. Sollte ja machbar sein :)

**Comment by a-v-l** [comment]
Ich hatte beim ersten Lightning Talk (#5) kurz erwähnt, dass von den [freiburger-freelancer](http://www.freiburger-freelancer.de/) am 06.05. ein Beratungstreffen über das Thema Haftpflichtversicherung für Webentwickler veranstaltet wird. Leider ist die Raumkapazität für diesen Termin bereits ausgelastet, so dass ich keine weiteren Interessenten mitnehmen kann. Falls Interesse besteht, kann ich aber fleißig mitschreiben und in unserer Runde dazu einen eigenen Lightning Talk anbieten…

**Comment by nicki-schinow** [comment]
Ein Lightning Talk wäre super!
