### ISSUE TITLE
[Lightning Talks] 28. April 2014

### ISSUE THREAD

**Issue by sebald** [devsmeetup/forum#5]
Wir sind auf der Suche nach ein paar [Lightning Talks](http://en.wikipedia.org/wiki/Lightning_talk). Wenn ihr Bock habt kurz über ein Thema mit anschließender Diskussion zu reden, postet hier euren Vorschlag!

**Es ist nicht notwendig, dass ihr viel über das Thema wisst, die Talks sollen vor allem dazu dienen eine Diskussion anzuregen.** Die Talks sind deswegen auch eine super Gelegenheit für euch Meinungen über ein Thema einzuholen, das euch schon lange interessiert!!!

Falls ihr ein bisschen Inspiration braucht: https://www.youtube.com/watch?v=wK63eUyk-iM
### Lightning Talks
1. **Git & Deploy auf verschiedenen Servern** von @nimius-nicki 
2. **The art of writing bug reports or - how to sell a movie plot to Hollywood?** von @stmllr 
3. **Rewriting History with Git** @jayeff

**Comment by nicki-schinow** [comment]
**Thema: Git & Deploy auf verschiedenen Servern**
• Wie geht man mit Konfigurationsfiles um?
• Symlinks und Dependencies?
• …

**Comment by stmllr** [comment]
Thema: "The art of writing bug reports or - how to sell a movie plot to Hollywood?" by Steffen Müller

**Comment by sebald** [comment]
@stmllr +1000000000000

Vor allem für Nicht-Techniker! ;)

**Comment by a-v-l** [comment]
**Thema: your next webapp _from scratch_**
(anhand eines konkreten Beispiels)
- vom Konzept zur Umsetzung
- welche Tools werden eingesetzt
- welche Strategien helfen bei der Auswahl
- …

**Comment by sebald** [comment]
@stmllr War das ein Vorschlag, den du halten würdest?

@a-v-l Wir hatten so einen Talk im Januar. Würde sich dein Talk von dem unterscheiden?

**Comment by jayeff** [comment]
Bei Interesse kann ich eine Kurzeinführung in **Rewriting History with Git** geben.

@sebald Wie viel Minuten Präsentation pro Thema würdest du grob veranschlagen?

**Comment by a-v-l** [comment]
@sebald Ja ich war auch dabei: Devs Toolkit… Das »anhand eines konkreten Beispiels« ist vielleicht ein bisschen irreführend.

Ich wollte weniger ein schon fertiges Projekt vorstellen, als vielmehr eine Diskussion anregen, wie man von der ersten Ideenskizze an vorgeht. Also: Idee analysieren. Was für Anforderungen stellt diese Idee an den Entwickler? Anhand welcher Kriterien wählt man sein »Toolkit« aus? Und so weiter und so fort…
Konkret daran ist nur eine Idee von mir zu einem "colaboration board" anhand dessen man Beispielhaft das Für und Wider z.B. von Angular.js vs Backbone.js vs Ember.js diskutieren könnte. Vielleicht ist das Ganze aber auch zu viel für ein `Lightning Talk`?

**Comment by stmllr** [comment]
Lightning talks kenne ich als 5-Minüter. Wie bei Twitter auch steigert die strikte Begrenzung den Wert ungemein.

**Comment by nicodh** [comment]
@a-v-l Wäre ein spannendes Thema vor allem wenn verschiedene Strategien/Frameworks/Tools verglichen/diskutiert würden (genug Leute haben wir dafür ja).
Aber sicher zu umfangreich für ein Lightning Talk. Gerne beim nächsten Meetup

**Comment by a-v-l** [comment]
@nicodh Genau so hatte ich mir das auch vorgestellt: Als Diskussionsgrundlage. Dann hätten wir ja schon mal das nächste Meetup gesichert… (Ist mir auch recht – bis zum 28. habe ich kaum Zeit was Ordentliches vorzubereiten)

**Comment by sebald** [comment]
@nicodh @a-v-l Für Finde das Thema auch super. Aber man müsste zumindest einen Rahmen geben. Christian hat Ruby abgedeckt, aber es gibt ja noch genug andere Sprachen/Stacks! :)

PS: Für Mai haben wir schon von Tobias ein Talk :) Aber im Juni dann!

@all ich werde mal ganz oben eine Liste machen damit wir einen Überblick bekommen.

**Comment by sebald** [comment]
Bisher sind die Talks dank Nimius vllt etwas Git lastig :D
@a-v-l deinen hab ich erst mal weggelassen, ist das ok? Und du hältst dann einen Talk im Juni (oder wann auch immer du kannst :) )

**Comment by jayeff** [comment]
@stmllr

> Lightning talks kenne ich als 5-Minüter.

Ich auch. Mit Zwischenfragen und Diskussion sind 5 Minuten aber doch recht knapp. ;-)

**Comment by a-v-l** [comment]
@jayeff & @stmllr: 5min Talk & 20-30min Diskussion – sonst wären wir bei 3 Präsentationen ja auch schon nach einer ¼ Stunde fertig.

@sebald: Juni ist super. Wegen dem Rahmen werde ich mir was überlegen. Eventuell mache ich hier vorab ein Issue auf, so das ihr auch was beisteuern könnt bzw um sicher zu gehen, dass die entsprechenden Spezialisten auch zugegen sind (für die Diskussion im Anschluss).

**Comment by sebald** [comment]
Genau. Üblicherweise gehen bei uns die Tags ~2 Std, was ich etwas arg lang finde. Wenn wir 3-4 Talks (5min) + anschließende Diskussion (25min) sollte es reichen :)

**Comment by sebald** [comment]
@nicodh @jayeff @stmllr könnt ihr mir bitte eure Slides bis zum 25. April schicken? :) Ich würde die dann alle auf meinen Rechner packen, so dass wir zwischen den Talks noch groß rumwurschteln müssen.

**Comment by nicodh** [comment]
Du meinst @nimius-nicki . Ich habe ja keinen Talk...

**Comment by sebald** [comment]
... eure Kürzel fangen beide gleich an. Sorry! :D

**Comment by sebald** [comment]
@nimius-nicki @jayeff @stmllr Remember, remember the ~~5. of November~~ 28. of April!!! I need some Slides!

**Comment by jayeff** [comment]
@sebald habe keine Slides - live gitting.

dein oder mein Rechner dürfte keinen großen Unterschied machen.

**Comment by sebald** [comment]
Alles klar. Danke für die Rückmeldung!
