### ISSUE TITLE
[Vortrag] Domain Driven Design & NoSQL

### ISSUE THREAD

**Issue by mchacki** [devsmeetup/forum#7]
Huhu,

ich hoffe das hier ist die richtige Stelle.

ich würde gerne an einem der nächsten Treffen einen Vortrag mit folgendem Inhalt halten (ca. 30min):

Domain Driven Design ist ein Softwareentwicklungsprozess dessen Fokus auf der Findung einer gemeinsamen Sprache aller involvierten Parteien liegt. Diese Sprache und die daraus resultierenden Modelle kommen oft von der Fachseite und nicht aus dem technischen Details der Implementierung. Das Ziel ist die Verbesserung der Kommunikation zwischen Kunden, Entwicklern und allen anderen involvierten Gruppen. Auch wenn Eric Evans Buch über dieses Thema fast 10 Jahre alt ist: Das Thema bleibt wichtig weil weiterhin viele Projekte aufgrund von Kommunikationsproblemen scheitern.

Relationale Datenbanken haben ihre eigene Sprache und beeinflussen das Design von Software, welches es weiter von der Domäne entfernt: Entitäten werden nur deswegen erstellt um den Entwurf nach Best Practices für relationale Datenbanken zu entsprechen. Zwei Arten von NoSQL Datenbanken ändern dies: Document Stores und Graphendatenbanken. In einem Document Store können 'Enthält' Relationen auf eine natürliche Art modelliert werden. Eine Graphendatenbank erlaubt es die Beziehung zwischen Objekten in der Sprache der Domäne abzubilden.

Ich möchte zeigen wie Multi-Model Datenbanken (jene die Document Stores und Graphendatenbanken kombinieren) dir helfen können dein Problem auf eine Art so zu modellieren, dass es für alle beteiligten Gruppen verständlich ist.

**Comment by sebald** [comment]
Hi Michael,

ja, das ist der richtige Ort! :)

Super, dass du Lust hast einen Talk zu halten. Für das nächste Meetup haben wir schon einen Talk ( siehe #6). Im Juni wollte, soweit ich weiß, @a-v-l einen Vortrag halten, falls das noch aktuell ist.

Könntest du auch im Juli?

**Comment by stmllr** [comment]
Yeah! DDD #ftw

**Comment by a-v-l** [comment]
@mchacki & @sebald Würde meinen Vortrag gerne etwas verschieben, da ich gerade einen Büroumzug und einen dichten Projektplan zu bewältigen habe – Juni wäre für DDD&NoSQL also noch zu haben…

**Comment by sebald** [comment]
Oki, also wenn du magst, könntest du dann im Juni deinen Talk halten. Würde mich sehr freuen, wenn das klappt!

**Comment by mchacki** [comment]
@sebald Von mir aus kann ich den Vortrag auch gerne im Juni halten wenn das Terminlich passt
Wäre das dann der 25.06. ?
Das würde bei mir gehen.

**Comment by sebald** [comment]
Jep, genau :)

**Comment by sebald** [comment]
Hi Michael, für deinem Vortrag brauchen wir noch ein paar Dinge für die Webseite.
- Bild von dir
- Twitter Handle
- Mini Bio
- Kurzintro zum Thema

**Comment by sebald** [comment]
@mchacki ping :) siehe vorheriges comment!

**Comment by mchacki** [comment]
Huhu, sorry, war etwas im Stress ;)

Bild: Von Gravatar: http://1.gravatar.com/avatar/c847f05226c5ce85bea560291f481226?s=512
Twitter Handle: @mchacki
Mini Bio:
Michael ist ein JavaScript und NoSQL enthusiast. In seiner Freizeit organisiert er cologne.js die JavaScript User Group in Köln. Diese findet alle zwei Monate statt. Michael hat einen Master of Science Abschluss der RWTH Aachen in Informatik. Im Beruf wirkt er als Kernentwickler der ArangoDB mit und ist dort vor allem zuständig für das Web Interface und Graphen-funktionalität.
Michael ist regelmäßiger Sprecher auf diversen User Groups in ganz Deutschland.

Kurzintro:
Domain Driven Design ist ein Softwareentwicklungsprozess dessen Fokus auf der Findung einer gemeinsamen Sprache aller involvierten Parteien liegt. Diese Sprache und die daraus resultierenden Modelle kommen oft von der Fachseite und nicht aus dem technischen Details der Implementierung. Das Ziel ist die Verbesserung der Kommunikation zwischen Kunden, Entwicklern und allen anderen involvierten Gruppen. Auch wenn Eric Evans Buch über dieses Thema fast 10 Jahre alt ist: Das Thema bleibt wichtig weil weiterhin viele Projekte aufgrund von Kommunikationsproblemen scheitern.

Relationale Datenbanken haben ihre eigene Sprache und beeinflussen das Design von Software, welches es weiter von der Domäne entfernt: Entitäten werden nur deswegen erstellt um den Entwurf nach Best Practices für relationale Datenbanken zu entsprechen. Zwei Arten von NoSQL Datenbanken ändern dies: Document Stores und Graphendatenbanken. In einem Document Store können 'Enthält' Relationen auf eine natürliche Art modelliert werden. Eine Graphendatenbank erlaubt es die Beziehung zwischen Objekten in der Sprache der Domäne abzubilden.

@sebald 
Hoffe das ist ausreichend.

**Comment by sebald** [comment]
Hiho. Super, danke! :) Werde übers WE die Webseite aktualisieren.
Sag bescheid wenn du noch ne Info brauchst.

Unser Beamer hat ein VGA/DVI-Anschluss und wir haben Adapter für MiniDisplay-Port.

**Comment by sebald** [comment]
Webseite aktualisiert! :)

**Comment by sebald** [comment]
@mchacki Sag bescheid, wenn du noch was brauchst oder wissen willst!

Du kommst ja nicht aus Freiburg. Soll dich jemand von irgendwo abholen bzw. kennst du dich hier aus?
