### ISSUE TITLE
[Lightning Talks] 30. Juli 2014

### ISSUE THREAD

**Issue by sebald** [devsmeetup/forum#8]
Hi zusammen,

am 30. Juli ist es wieder so weit: Das nächste Devsmeetup steht an!
Bevor wir im August eine Sommerpause machen, würden wir gerne noch einmal eine Runde Lightning Talks veranstalten.

Dafür brauchen wir natürlich drei Freiwillige!
Wenn ihr also umbedingt was loswerden wollt, meldet euch in diesem Issue! :)

**Comment by stmllr** [comment]
Ich wünsche mir einen Talk/Diskussion zum Thema "Profiling"

**Comment by drublic** [comment]
> Ich wünsche mir einen Talk/Diskussion zum Thema "Profiling"

Au ja, vor allem server-seitig. Bin nur leider nicht da :(

**Comment by sebald** [comment]
Bei Interesse würde ich einen kleinen Talk zu "Web Components" oder "Technical Debt" halten.
